u3a-siteworks-development/u3a-siteworks-core

classes/class-u3a-group.php, readme.txt, u3a-siteworks-core.php
Change agreed by change board 24th Nov
=> Bug 983 Remove 2nd prefix when showing group leaders

classes/class-u3a-group.php, css/u3a-custom-post-types.css, readme.txt
I think I'm requesting to merge bd-change-button-labels into release-1.0.0
=> Bd change group button labels

classes/class-u3a-common.php, classes/class-u3a-group.php, js/u3a-cpt-ensure-title.js
Also include u3a_notices in this.
=> Change error message when no title

classes/class-u3a-group.php, css/u3a-custom-post-types.css, js/u3a-group-blocks.js, readme.txt
I think this is the right way - just wasnt sure if I could have had conditional css in a better way
=> feature 1002: choice of across or down alphabetic groups

classes/class-u3a-event.php, classes/class-u3a-group.php, readme.txt
Same change as for "main" but backported to "release"
=> Release nt 1004 add support to display metadata for MFB

classes/class-u3a-event.php, css/u3a-custom-post-types.css, js/u3a-event-blocks.js
Also top margin of event set to 24px, and not Title Case on heading h3.
=> Fix bug in bgcolor options setting

classes/class-u3a-group.php
Just put into main on the quiet.
=> Change grouplist button capitalisation

inc/restapi.php, readme.txt
Extend the support for access to CPT metadata to include some Event data
=> 491 make some event metadata available via REST API

classes/class-u3a-group.php, readme.txt, u3a-siteworks-core.php
Similar change as made to main branch.
=> 1027 - more corrections for "category" in u3a group list

classes/class-u3a-group.php
Anchor groups when clicking the sort order buttons
=> es-dev-12 - maintain position on group list

classes/class-u3a-admin.php
Issue identified during testing of core release 1.0.8.  Same change as in main
=> 1027 set maxlength on category term input fields

classes/class-u3a-event.php
Add missing pattern rule to metabox field definition for new eventTime field.
=> 1015 Add pattern rule for eventTime

classes/class-u3a-group.php, readme.txt
Alter group status code "Suspended" to"Dormant".  Update readme.txt
=> 1032 change group status status "Suspended" to "Dormant"

classes/class-u3a-group.php, js/u3a-event-blocks.js, readme.txt
=> Release 1098 feedback presentation issues

classes/class-u3a-event.php, css/u3a-custom-post-types.css, js/u3a-event-blocks.js
add toggle button to layout settings if the layout includes featured images.
=> make eventlist images cropped or scaled

readme.txt, u3a-siteworks-core.php
merge 1.1.0 label back into main
=> Release 1.1.0 initial commit

classes/class-u3a-event.php, js/u3a-event-blocks.js
allow the user to switch off the title for event lists
=> 1034 allow toggle of title visibility

u3a-siteworks-core.php
Set Version and related define for version 1.1.2 in u3a-siteworks-core.php
=> increment version number in main plugin file

classes/class-u3a-admin.php, classes/class-u3a-group.php
=> Mc issue99

inc/traits.php
Description of the change in the task (85).
=> show dates on event refs

readme.txt, u3a-siteworks-core.php
Updates to readme.txt to document changes.
Increment version number,
Indicate tested with WP 6.6.
=> prepare for 1.1.3 point release

classes/class-u3a-event.php, classes/class-u3a-group.php, inc/update-siteworks-data.php, readme.txt, u3a-siteworks-core.php
I think this is now ready. I have tested on as many sample content texts as I can, and done one full test on an old Local site which needed 20 wp_posts changing.
I have also removed all refs to the old attributes in the code as they are no longer needed.
We should also make this into version 1.1.4 when merged into main and issue it!
=> Mc update db to v4

inc/traits.php
The list of events returned by list-events was filtered (if the user was not administrator), so the displayed list is only those in the future. However the same function is used to check whether a venue can be deleted, so non-admin users who have edit rights could be allowed to delete venues referenced by events in the past.
Rather than passing the event date out of the function, which would have needed modifications to the array passed out, I have
given the function an extra parameter to say whether to apply filtering. For the checking of deletability, this param is false, and for display, the param is true.
=> dont filter events when listing for possible deletion protection

classes/class-u3a-venue.php, js/u3a-venue-blocks.js
In part just commented out.
I've done a quick test to see the block no longer appears as an option
=> remove venuelist block

classes/class-u3a-group.php, readme.txt, u3a-siteworks-core.php
Note - same wording change also required in import/export plugin
=> 1094 change group status short text "Waiting list"

inc/traits.php
A minor revision to Ed's PR but only adding quotes around titles when the text is being generated for a search results page, so leaving the normal posts page as before.
=> NT es format variation

inc/traits.php
=> possible alt solution for excerpts

inc/traits.php
This would mask the issue - if we want to do so.
=> workround for duplicate xrefs

classes/class-u3a-notice.php, js/u3a-notice-blocks.js
Work Package 1105
The new properties are:
- Whether to use the Notice start date or end date for sorting
- Whether to sort Ascending or Descending
- The maximum number of Notices to return
=> Add new properties to the 'u3a notice list' block

classes/class-u3a-group.php
=> uppercase first letter when needed

classes/class-u3a-event.php
Nick requested hold-off on this one until documentation has time to catch up
=> temp backout of author edit until docs catch up

classes/class-u3a-group.php
Conversion of query parameters with ampersands to avoid them being split into separate _GET params.
=> fix for openproject1137

classes/class-u3a-notice.php
=> fix for 1142
